# Generated by Django 6.0.2 on 2026-09-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='ck_producto_precio_no_negativo'),
        ),
    ]
