# Generated by Django 6.0.2 on 2026-09-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_ck_producto_precio_no_negativo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='ck_producto_precio_no_negativo',
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='ck_producto_precio_positivo'),
        ),
    ]
