# Generated by Django 6.0.2 on 2026-03-10 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja (Sesión)',
                'verbose_name_plural': 'Cajas (Sesiones)',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja_sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.cajasesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-creado_en'],
            },
        ),
    ]
