# Generated by Django 6.0.2 on 2026-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'QR')], max_length=12, null=True),
        ),
    ]
