# Generated by Django 6.0.2 on 2026-09-11 11:51

from django.conf import settings
from django.db import migrations, models


def convertir_ajustes(apps, schema_editor):
    MovimientoCaja = apps.get_model("caja", "MovimientoCaja")
    MovimientoCaja.objects.filter(tipo="AJUSTE").update(tipo="AJUSTE_IN")


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_movimientocaja_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(convertir_ajustes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('ANULACION', 'Anulación de venta'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE_IN', 'Ajuste positivo'), ('AJUSTE_OUT', 'Ajuste negativo')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='uq_caja_una_sesion_abierta'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='uq_usuario_una_caja_abierta'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.CheckConstraint(condition=models.Q(('monto_apertura__gte', 0)), name='ck_caja_monto_apertura_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.CheckConstraint(condition=models.Q(('monto_cierre_declarado__isnull', True), ('monto_cierre_declarado__gte', 0), _connector='OR'), name='ck_caja_monto_cierre_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_mov_caja_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metodo_pago__isnull', False), ('tipo__in', ['VENTA', 'ANULACION'])), models.Q(('metodo_pago__isnull', True), ('tipo__in', ['INGRESO', 'EGRESO', 'AJUSTE_IN', 'AJUSTE_OUT'])), _connector='OR'), name='ck_mov_caja_metodo_consistente'),
        ),
    ]
