# Generated by Django 6.0.2 on 2026-09-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asegurar_esquema_caja(apps, schema_editor):
    Caja = apps.get_model("caja", "Caja")
    CajaSesion = apps.get_model("caja", "CajaSesion")
    connection = schema_editor.connection
    tablas = set(connection.introspection.table_names())

    if Caja._meta.db_table not in tablas:
        schema_editor.create_model(Caja)
        tablas = set(connection.introspection.table_names())

    tabla_habilitados = Caja._meta.get_field(
        "usuarios_habilitados"
    ).remote_field.through
    if tabla_habilitados._meta.db_table not in tablas:
        schema_editor.create_model(tabla_habilitados)

    with connection.cursor() as cursor:
        columnas = {
            columna.name
            for columna in connection.introspection.get_table_description(
                cursor, CajaSesion._meta.db_table
            )
        }

    tabla_sesion = schema_editor.quote_name(CajaSesion._meta.db_table)
    if "observacion_diferencia" not in columnas:
        schema_editor.execute(
            f"ALTER TABLE {tabla_sesion} "
            "ADD COLUMN observacion_diferencia varchar(255) NOT NULL DEFAULT ''"
        )
    if "caja_id" not in columnas:
        tabla_caja = schema_editor.quote_name(Caja._meta.db_table)
        schema_editor.execute(
            f"ALTER TABLE {tabla_sesion} ADD COLUMN caja_id bigint NULL "
            f"REFERENCES {tabla_caja} (id) DEFERRABLE INITIALLY DEFERRED"
        )


def preparar_datos_legacy(apps, schema_editor):
    Caja = apps.get_model("caja", "Caja")
    CajaSesion = apps.get_model("caja", "CajaSesion")
    MovimientoCaja = apps.get_model("caja", "MovimientoCaja")

    usuario_ids = list(
        CajaSesion.objects.values_list("usuario_id", flat=True).distinct()
    )
    if usuario_ids:
        caja_principal, _ = Caja.objects.get_or_create(
            numero="1",
            defaults={"nombre": "Principal", "activa": True},
        )
        CajaSesion.objects.filter(caja__isnull=True).update(caja=caja_principal)
        caja_principal.usuarios_habilitados.add(*usuario_ids)

    MovimientoCaja.objects.filter(tipo="AJUSTE").update(tipo="AJUSTE_IN")
    MovimientoCaja.objects.filter(
        tipo__in=["VENTA", "ANULACION"],
        metodo_pago__isnull=True,
    ).update(metodo_pago="efectivo")
    MovimientoCaja.objects.exclude(
        tipo__in=["VENTA", "ANULACION"],
    ).exclude(metodo_pago__isnull=True).update(metodo_pago=None)


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_movimientocaja_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Caja',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('numero', models.CharField(max_length=20, unique=True)),
                        ('nombre', models.CharField(blank=True, max_length=100)),
                        ('activa', models.BooleanField(default=True)),
                        ('usuarios_habilitados', models.ManyToManyField(blank=True, related_name='cajas_habilitadas', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Caja',
                        'verbose_name_plural': 'Cajas',
                        'ordering': ['numero'],
                    },
                ),
                migrations.AddField(
                    model_name='cajasesion',
                    name='observacion_diferencia',
                    field=models.CharField(blank=True, default='', max_length=255),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='cajasesion',
                    name='caja',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='sesiones',
                        to='caja.caja',
                    ),
                ),
            ],
        ),
        migrations.RunPython(asegurar_esquema_caja, migrations.RunPython.noop),
        migrations.RunPython(preparar_datos_legacy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cajasesion',
            name='caja',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sesiones',
                to='caja.caja',
            ),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('ANULACION', 'Anulación de venta'), ('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE_IN', 'Ajuste positivo'), ('AJUSTE_OUT', 'Ajuste negativo')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='uq_caja_una_sesion_abierta'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('usuario',), name='uq_usuario_una_caja_abierta'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.CheckConstraint(condition=models.Q(('monto_apertura__gte', 0)), name='ck_caja_monto_apertura_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.CheckConstraint(condition=models.Q(('monto_cierre_declarado__isnull', True), ('monto_cierre_declarado__gte', 0), _connector='OR'), name='ck_caja_monto_cierre_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_mov_caja_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metodo_pago__isnull', False), ('tipo__in', ['VENTA', 'ANULACION'])), models.Q(('metodo_pago__isnull', True), ('tipo__in', ['INGRESO', 'EGRESO', 'AJUSTE_IN', 'AJUSTE_OUT'])), _connector='OR'), name='ck_mov_caja_metodo_consistente'),
        ),
    ]
