# Generated by Django 6.0.2 on 2026-09-11 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_movimientocaja_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='idx_caja_estado_fecha'),
        ),
    ]
