# Generated by Django 6.0.2 on 2026-09-11 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cajasesion_idx_caja_estado_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ABIERTA'), ('fecha_cierre__isnull', True), ('monto_cierre_declarado__isnull', True)), models.Q(('estado', 'CERRADA'), ('fecha_cierre__isnull', False), ('monto_cierre_declarado__isnull', False)), _connector='OR'), name='ck_caja_estado_cierre_consistente'),
        ),
    ]
