# Generated by Django 6.0.2 on 2026-09-11 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0002_producto_ck_producto_precio_no_negativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'AJUSTE'), models.Q(('cantidad__gt', 0), ('tipo__in', ['ENTRADA', 'SALIDA'])), _connector='OR'), name='ck_mov_stock_cantidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='ck_stock_cantidad_no_negativa'),
        ),
    ]
