# Generated by Django 5.1.4 on 2026-10-03 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrar_movimientos_historicos(apps, schema_editor):
    Movimiento = apps.get_model("inventario", "MovimientoStock")
    Stock = apps.get_model("inventario", "Stock")
    Producto = apps.get_model("productos", "Producto")
    stocks = dict(Stock.objects.values_list("producto_id", "cantidad"))
    tipos = dict(Producto.objects.values_list("id", "tipo"))
    for producto_id in Movimiento.objects.values_list("producto_id", flat=True).distinct():
        actual = stocks.get(producto_id, 0)
        movimientos = Movimiento.objects.filter(producto_id=producto_id).order_by("-creado_en", "-pk")
        for movimiento in movimientos:
            cantidad_original = movimiento.cantidad
            if movimiento.tipo == "SALIDA":
                delta = -abs(cantidad_original)
                tipo_nuevo = "VENTA"
            elif movimiento.tipo == "ENTRADA":
                delta = abs(cantidad_original)
                tipo_nuevo = "AJUSTE_POSITIVO"
            else:
                delta = cantidad_original
                tipo_nuevo = "AJUSTE_POSITIVO" if delta > 0 else "AJUSTE_NEGATIVO"
            anterior = actual - delta
            if anterior < 0:
                anterior = 0
            Movimiento.objects.filter(pk=movimiento.pk).update(
                tipo=tipo_nuevo,
                cantidad=delta,
                tipo_articulo=tipos.get(producto_id, "PRODUCTO_REVENTA"),
                stock_anterior=anterior,
                stock_resultante=actual,
                referencia_tipo="historico",
            )
            actual = anterior


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_completar_stock_productos'),
        ('productos', '0004_unidades_y_tipos_articulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Detalle de orden de compra',
                'verbose_name_plural': 'Detalles de órdenes de compra',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                'verbose_name': 'Detalle de recepción de compra',
                'verbose_name_plural': 'Detalles de recepciones de compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('PRODUCTO_REVENTA', 'Producto de reventa'), ('INSUMO', 'Insumo')], db_index=True, max_length=24)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PARCIALMENTE_RECIBIDA', 'Parcialmente recibida'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=25)),
                ('fecha', models.DateField()),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-numero'],
                'permissions': [('emitir_ordencompra', 'Puede emitir órdenes de compra'), ('cancelar_ordencompra', 'Puede cancelar órdenes de compra'), ('recibir_ordencompra', 'Puede recibir órdenes de compra')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=180)),
                ('ruc', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('persona_contacto', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recepción de compra',
                'verbose_name_plural': 'Recepciones de compra',
                'ordering': ['-fecha_recepcion', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaOrdenCompra',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de orden de compra',
                'verbose_name_plural': 'Secuencias de órdenes de compra',
            },
        ),
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-creado_en', '-pk'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.RemoveConstraint(
            model_name='movimientostock',
            name='ck_mov_stock_cantidad_valida',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='referencia_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='referencia_tipo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='stock_resultante',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='tipo_articulo',
            field=models.CharField(choices=[('PRODUCTO_REVENTA', 'Producto de reventa'), ('INSUMO', 'Insumo'), ('PRODUCTO_ELABORADO', 'Producto elaborado')], default='PRODUCTO_REVENTA', max_length=24),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por compra'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('VENTA', 'Venta'), ('PRODUCCION_ENTRADA', 'Entrada de producción'), ('PRODUCCION_CONSUMO', 'Consumo de producción'), ('ANULACION', 'Anulación'), ('OTRO', 'Otro')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.RunPython(migrar_movimientos_historicos, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', 'creado_en'], name='idx_mov_stock_producto_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['referencia_tipo', 'referencia_id'], name='idx_mov_stock_referencia'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='ck_mov_stock_cantidad_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_anterior__gte', 0)), name='ck_mov_stock_anterior_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_resultante__gte', 0)), name='ck_mov_stock_resultante_no_negativo'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.unidadmedida'),
        ),
        migrations.AddField(
            model_name='detallerecepcioncompra',
            name='detalle_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='inventario.detalleordencompra'),
        ),
        migrations.AddField(
            model_name='detallerecepcioncompra',
            name='movimiento_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_recepcion', to='inventario.movimientostock'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='usuario_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallerecepcioncompra',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventario.recepcioncompra'),
        ),
        migrations.AddConstraint(
            model_name='detalleordencompra',
            constraint=models.UniqueConstraint(fields=('orden_compra', 'producto'), name='uq_oc_producto'),
        ),
        migrations.AddConstraint(
            model_name='detalleordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_solicitada__gt', 0)), name='ck_detalle_oc_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detalleordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0)), name='ck_detalle_oc_costo_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', 'fecha'], name='idx_oc_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'fecha'], name='idx_oc_proveedor_fecha'),
        ),
        migrations.AddConstraint(
            model_name='detallerecepcioncompra',
            constraint=models.UniqueConstraint(fields=('recepcion', 'detalle_orden'), name='uq_recepcion_detalle_oc'),
        ),
        migrations.AddConstraint(
            model_name='detallerecepcioncompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_recibida__gt', 0)), name='ck_recepcion_cantidad_positiva'),
        ),
    ]
