# Generated by Django 6.0.2 on 2026-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
