# Generated by Django 6.0.2 on 2026-05-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'QR')], max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Pago de venta',
                'verbose_name_plural': 'Pagos de venta',
            },
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='uq_ventas_producto_categoria_nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='ventapago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
