# Generated by Django 6.0.2 on 2026-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_ticket',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
