# Generated by Django 6.0.2 on 2026-09-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def preparar_datos(apps, schema_editor):
    Venta = apps.get_model("ventas", "Venta")
    VentaPago = apps.get_model("ventas", "VentaPago")
    SecuenciaTicket = apps.get_model("ventas", "SecuenciaTicket")

    ultimo = Venta.objects.aggregate(numero=Max("numero_ticket"))["numero"] or 0
    SecuenciaTicket.objects.update_or_create(
        nombre="venta", defaults={"ultimo_numero": ultimo}
    )

    for pago in VentaPago.objects.all():
        pago.monto_recibido = pago.monto
        pago.save(update_fields=["monto_recibido"])

    for venta in Venta.objects.exclude(vuelto=0):
        restante = venta.vuelto
        pagos_efectivo = list(
            VentaPago.objects.filter(venta=venta, metodo_pago="efectivo").order_by("-pk")
        )
        for pago in pagos_efectivo:
            if restante <= 0:
                break
            descuento = min(restante, pago.monto)
            pago.monto -= descuento
            restante -= descuento
            if pago.monto > 0:
                pago.save(update_fields=["monto"])
            else:
                pago.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_movimientocaja_tipo_and_more'),
        ('clientes', '0001_initial'),
        ('productos', '0002_producto_ck_producto_precio_no_negativo'),
        ('ventas', '0004_venta_numero_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaTicket',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de ticket',
                'verbose_name_plural': 'Secuencias de tickets',
            },
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'permissions': [('view_global_reports', 'Puede ver reportes globales de ventas'), ('cancel_venta', 'Puede anular ventas')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ventapago',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(preparar_datos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_venta_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('vuelto__gte', 0)), name='ck_venta_vuelto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ck_detalle_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ck_detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ventapago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ventapago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_recibido__isnull', True), ('monto_recibido__gte', models.F('monto')), _connector='OR'), name='ck_pago_recibido_mayor_aplicado'),
        ),
    ]
