# Generated by Django 6.0.2 on 2026-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_secuenciaticket_alter_venta_options_venta_anulada_en_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ventapago',
            name='ck_pago_recibido_mayor_aplicado',
        ),
        migrations.AlterField(
            model_name='ventapago',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='ventapago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_recibido__gte', models.F('monto'))), name='ck_pago_recibido_mayor_aplicado'),
        ),
    ]
