# Generated by Django 6.0.2 on 2026-09-11 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cajasesion_idx_caja_estado_fecha'),
        ('clientes', '0001_initial'),
        ('ventas', '0006_remove_ventapago_ck_pago_recibido_mayor_aplicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha'], name='idx_venta_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario', 'fecha'], name='idx_venta_usuario_fecha'),
        ),
    ]
