# Generated by Django 6.0.2 on 2026-09-11 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cajasesion_ck_caja_estado_cierre_consistente'),
        ('clientes', '0001_initial'),
        ('ventas', '0008_completar_numeros_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anulada_en__isnull', True), ('anulada_por__isnull', True), ('estado', 'CONFIRMADA'), ('motivo_anulacion', '')), models.Q(('anulada_en__isnull', False), ('anulada_por__isnull', False), ('estado', 'ANULADA'), models.Q(('motivo_anulacion', ''), _negated=True)), _connector='OR'), name='ck_venta_anulacion_consistente'),
        ),
    ]
